services:
    _defaults:
        autowire: true
        autoconfigure: true

    Jaspersoft\Client\Client:
        arguments: ["%wizhippo_jasper_client.url%", "%wizhippo_jasper_client.username%", "%wizhippo_jasper_client.password%", "%wizhippo_jasper_client.organization%"]

    Wizhippo\Bundle\JasperClientBundle\Helper\JasperServerFormHelper: ~
